services:
  - type: web
    name: poultry-website
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT project.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poultry_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: doixo5oiw
      - key: CLOUDINARY_API_KEY
        value: 435759228322341
      - key: CLOUDINARY_API_SECRET
        value: H3_ZVEXWGcyuE28IfKWUYsTo5sY
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DEBUG
        value: "False"
      - key: REDIS_URL
        value: redis://your_redis_url_here  # set this manually on Railway
      - key: ALLOWED_HOSTS
        value: "yourdomain.com,localhost,127.0.0.1"
databases:
  - name: poultry_db
    plan: free
